CREATE SEQUENCE CATEGORY_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 20
    KEEP;

CREATE TABLE CATEGORY_TAB (
    ID INTEGER DEFAULT CATEGORY_SEQ.NEXTVAL,
    NAME VARCHAR2(20) NOT NULL,
    CONSTRAINT CATEGORY_PK PRIMARY KEY (ID)
) TABLESPACE APP_TBS;
CREATE INDEX CATEGORY_NAME_IDX ON CATEGORY_TAB(NAME);

ALTER TABLE PET_TAB ADD CATEGORY_ID INTEGER ADD CONSTRAINT PET_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY_TAB(ID);

CREATE OR REPLACE EDITIONING VIEW CATEGORY AS
SELECT
    ID,
    NAME
FROM CATEGORY_TAB;

INSERT INTO CATEGORY (NAME) SELECT DISTINCT CATEGORY FROM PET_TAB;
UPDATE PET_TAB P SET P.CATEGORY_ID = (SELECT C.ID FROM CATEGORY C WHERE C.NAME = P.CATEGORY);

CREATE OR REPLACE EDITIONING VIEW PET AS
SELECT ID,
       NAME,
       PHOTO,
       TAGS,
       STATUS,
       CATEGORY_ID
FROM   PET_TAB;

-- ALTER TABLE PET_TAB DROP COLUMN CATEGORY;






